-- =============================================================================
-- Módulo 2027 — tabla estatus_2027
--
-- Proyecto Supabase: Contratos (hvabkxgxmthyqbgsjqgr). NO el de AIFA-OPERACIONES:
-- la aplicación sólo tiene sesión (auth) en este proyecto, y un token de un
-- proyecto no vale en el otro. Poner aquí la tabla es lo único que permite
-- cerrarla a usuarios autenticados en vez de dejarla abierta a la llave anónima
-- que viaja en el bundle del navegador.
--
-- Espejo de estatus_2026 (misma forma, para que las vistas de Resumen, Estatus
-- servicios y Gantt funcionen sin reescribirlas), con cuatro diferencias a
-- propósito:
--
--   1. Los montos son numeric(18,2), no texto con "$" y comas. La app ya sabe
--      leer ambos (parseNumericValue), pero en la tabla nueva el dato entra
--      validado y se puede sumar en SQL.
--   2. Las 22 columnas que de verdad guardan una fecha son date, no texto. El
--      Gantt se dibuja con ellas; en texto cabía "N/A" y rompía el cálculo.
--      Las cinco que históricamente sí traen texto libre ("Publicación de
--      Convocatoria", "Visita a las instalaciones", "Junta de Aclaraciones",
--      "Apertura de Proposiciones", "Fallo") se dejan text, igual que en 2026.
--   3. "ID" es IDENTITY. En 2026 el número lo calcula el navegador con
--      max(ID)+1 y dos personas dando de alta a la vez chocan; aquí la base lo
--      asigna. El cliente puede seguir mandándolo y también funciona.
--   4. RLS cerrada y bitácora en el servidor (ver secciones 5 y 7).
--
-- IDEMPOTENTE: se puede correr completo más de una vez sin duplicar nada.
-- =============================================================================

begin;

-- -----------------------------------------------------------------------------
-- 1) Tabla
-- -----------------------------------------------------------------------------
create table if not exists public.estatus_2027 (
  "ID"                                                integer generated by default as identity primary key,

  -- Identificación del servicio
  "Clave cucop"                                       text,
  "Nombre del Servicio."                              text,
  "Observación General del Servicio"                  text,
  "Subdirección"                                      text,
  "Gerencia"                                          text,
  "Responsable"                                       text,
  "Tipo_de_servicio"                                  text,
  "Fase"                                              text,
  "Estatus"                                           text,

  -- Montos
  "Monto solicitado anteproyecto 2027"                numeric(18,2),
  "Monto Máximo 2025"                                 numeric(18,2),
  "Monto Máximo 2026"                                 numeric(18,2),
  "Monto Máximo 2027"                                 numeric(18,2),
  "Monto de Suficiencia presupuestal"                 numeric(18,2),
  "Método Cálculo Monto Máximo"                       text,
  precio_prevaleciente                                double precision,
  monto_real_ejecutado                                double precision,

  -- Banderas de avance
  "Documentación soporte"                             boolean,
  "Investigación de mercado"                          boolean,
  "Suficiencia Presupuestal"                          boolean,
  "Procedimiento de contratación"                     boolean,
  "Póliza de Responsabilidad Civil"                   boolean,
  "Entregables por mes"                               boolean,
  "Garantía de cumplimiento"                          boolean,
  "Garantía de Calidad"                               boolean,
  convenio_modificatorio                              boolean not null default false,

  -- Procedimiento de contratación (texto libre: aquí sí caben "N/A" y dd/mm/aaaa)
  "No. de Procedimiento de contratación"              text,
  "Publicación de Convocatoria"                       text,
  "Visita a las instalaciones"                        text,
  "Junta de Aclaraciones"                             text,
  "Apertura de Proposiciones"                         text,
  "Fallo"                                             text,
  "Lista de asistencia."                              text,
  "Diferimiento de fallo"                             text,
  "Desierta"                                          text,

  -- Contrato resultante
  "Administrador de Contrato"                         text,
  "Proveedor"                                         text,
  "No. de contrato"                                   text,
  "Vigencia de inicio"                                text,
  "Vigencia de Término"                               text,
  "Fecha de firma de contrato"                        date,
  "Incidencias del servicio"                          text,

  -- Investigación de mercado (fechas reales)
  "Fecha de remisión de investigación de mercado"     date,
  "Fecha de recepción de investigación de mercado"    date,
  "Evaluación técnica"                                date,
  "Validación por el área"                            date,

  -- Las 18 fechas que dibujan el Gantt, en pares inicio/fin por cada una de
  -- las 9 etapas del proceso (ver GANTT_DATE_GROUPS en components/Dashboard.tsx).
  "Fecha inicio elaboración anexo técnico"            date,  -- 1. Anexo técnico
  "Fecha término elaboración anexo técnico"           date,
  "Fecha remisión IM"                                 date,  -- 2. En IM
  "Fecha recepción IM"                                date,
  "Fecha recepción IM área técnica"                   date,  -- 3. Recepción de IM
  "Fecha remisión área técnica"                       date,
  "Fecha inicio validación IM"                        date,  -- 4. Validación por el área
  "Fecha término validación IM"                       date,
  "Fecha recepción carpeta validada"                  date,  -- 5. Carpeta validada a RM
  "Fecha remisión carpeta RM"                         date,
  "Fecha envío revisión DEFENSA"                      date,  -- 6. Revisión DEFENSA
  "Fecha recepción revisión DEFENSA"                  date,
  "Fecha inicio atención observaciones"               date,  -- 7. Atención observaciones
  "Fecha remisión observaciones"                      date,
  "Fecha inicio documentación publicación"            date,  -- 8. Documentación
  "Fecha remisión documentación publicación"          date,
  "Fecha inicio publicación"                          date,  -- 9. Publicado Compras MX
  "Fecha fallo"                                       date,

  -- La app oculta estas dos columnas de la tabla (shouldSkipColumnForForm).
  created_at                                          timestamptz not null default timezone('utc', now()),
  updated_at                                          timestamptz not null default timezone('utc', now())
);

comment on table public.estatus_2027 is
  'Programa de contratación 2027. Espejo de estatus_2026 con montos y fechas '
  'tipados, ID asignado por la base y RLS por rol. La bitácora la escribe el '
  'trigger estatus_2027_audit, no el navegador.';

-- El estatus no es texto libre: son las 11 etapas del proceso, las mismas que
-- ofrece el selector de la app (ESTATUS_2026_OPTIONS). Sin esto, cualquiera con
-- la llave pública podría dejar un estatus inventado que ninguna vista sabe
-- pintar. Para agregar una etapa nueva: alter table ... drop constraint y
-- volver a crearla con el valor añadido.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'estatus_2027_estatus_valido'
  ) then
    alter table public.estatus_2027
      add constraint estatus_2027_estatus_valido check (
        "Estatus" is null or "Estatus" in (
          'Elaboración de anexo técnico, administrativo y apéndices',
          'En IM',
          'Recepción de IM',
          'Validación de IM por el área técnica',
          'Envío de carpeta validada a RM',
          'En revisión DEFENSA',
          'Atención de observaciones DEFENSA',
          'Documentación actualizada para publicación',
          'Publicado Compras MX',
          'Adjudicado',
          'Cancelado'
        )
      );
  end if;
end $$;

-- -----------------------------------------------------------------------------
-- 2) Índices — los que usan los filtros del módulo
-- -----------------------------------------------------------------------------
create index if not exists estatus_2027_estatus_idx      on public.estatus_2027 ("Estatus");
create index if not exists estatus_2027_subdireccion_idx on public.estatus_2027 ("Subdirección");
create index if not exists estatus_2027_gerencia_idx     on public.estatus_2027 ("Gerencia");
create index if not exists estatus_2027_responsable_idx  on public.estatus_2027 ("Responsable");

-- -----------------------------------------------------------------------------
-- 3) updated_at al día
-- -----------------------------------------------------------------------------
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists estatus_2027_touch_updated_at on public.estatus_2027;
create trigger estatus_2027_touch_updated_at
  before update on public.estatus_2027
  for each row execute function public.touch_updated_at();

-- -----------------------------------------------------------------------------
-- 4) Semilla: los 21 servicios del programa 2027
--
-- Clave cucop, nombre y monto son literales del oficio. Estatus y "Fecha
-- remisión IM" se derivan del texto de la columna Estatus de ese mismo oficio
-- ("En IM con fecha 21/08/2026" → etapa "En IM", remisión 2026-08-21), y el
-- texto original queda completo en "Observación General del Servicio" para
-- poder cotejarlo.
--
-- Subdirección, Gerencia, Responsable y Tipo_de_servicio NO venían en el
-- oficio: se heredan del mismo servicio en estatus_2026, para que el módulo
-- abra con los filtros y los agrupados ya funcionando. Fase queda en
-- 'Ordinaria'. Todo eso es editable desde la tabla de la app — conviene que el
-- área lo revise.
--
-- ON CONFLICT DO NOTHING: correr esta sección dos veces no duplica servicios.
-- -----------------------------------------------------------------------------
insert into public.estatus_2027 (
  "ID", "Clave cucop", "Nombre del Servicio.", "Monto solicitado anteproyecto 2027",
  "Subdirección", "Gerencia", "Responsable", "Tipo_de_servicio", "Fase",
  "Estatus", "Fecha remisión IM", "Fecha inicio validación IM",
  "Observación General del Servicio"
) values
  (1, '35901-0002',
   'Servicio de poda de áreas verdes en terreno natural, calles de rodaje, pistas y área operacional.',
   24440000.00, 'Subdirección de Ingeniería', 'Gerencia de Ingeniería Civil',
   'ADRIANA PEREZ MALDONADO', 'Normativo', 'Ordinaria',
   'Validación de IM por el área técnica', '2026-08-21', '2026-09-10',
   'En IM con fecha 21/08/2026. Validación de área 10/09/2026 (IM realizada).'),

  (2, '35102-0003',
   'Servicio de mantenimiento a instalaciones arquitectónicas.',
   35400000.00, 'Subdirección de Ingeniería', 'Gerencia de Ingeniería Civil',
   'GILBERTO AYALA RAMÍREZ', 'Ordinario - Media', 'Ordinaria',
   'En IM', '2026-08-21', null,
   'En IM con fecha 21/08/2026.'),

  (3, '35102-0003',
   'Servicio de mantenimiento a pavimentos del área de movimiento.',
   25772236.00, 'Subdirección de Ingeniería', 'Gerencia de Ingeniería Civil',
   'ADRIANA PEREZ MALDONADO', 'Ordinario - Media', 'Ordinaria',
   'En IM', '2026-08-21', null,
   'En IM con fecha 21/08/2026.'),

  (4, '35701-0001',
   'Servicio de mantenimiento a elevadores, escaleras y aceras eléctricas.',
   30900000.00, 'Subdirección de Ingeniería', 'Gerencia de Ingeniería Electromecánica',
   'IRMA KARINA VARGAS GARCÍA', 'Ordinario - Alta', 'Ordinaria',
   'En IM', '2026-08-20', null,
   'En IM con fecha 20/08/2026.'),

  (5, '35701-0001',
   'Servicio de mantenimiento al sistema de HVAC y equipos de bombeo e intercambiadores de agua helada y caliente.',
   33864480.00, 'Subdirección de Ingeniería', 'Gerencia de Ingeniería Electromecánica',
   'MONSERRAT ALONSO MARTÍNEZ', 'Ordinario - Alta', 'Ordinaria',
   'En IM', '2026-08-28', null,
   'En IM con fecha 28/08/2026.'),

  (6, '35701-0001',
   'Servicio de mantenimiento preventivo y correctivo a plantas potabilizadoras primaria, secundaria y red de agua potable: incluye la operación de los pozos.',
   25073242.00, 'Subdirección de Ingeniería', 'Gerencia de Ingeniería Civil',
   'ESMERALDA EMILY RODRÍGUEZ MARTÍNEZ', 'Ordinario - Alta', 'Ordinaria',
   'En IM', '2026-09-08', null,
   'En IM con fecha 08/09/2026.'),

  (7, '35701-0001',
   'Servicio de mantenimiento y conservación a plantas tratadoras de aguas residuales, red general de drenaje, incluye la operación de cárcamos del AIFA.',
   38646595.00, 'Subdirección de Ingeniería', 'Gcia. Op. y Mtto de Inst. Hidráulicas',
   'ESMERALDA EMILY RODRÍGUEZ MARTÍNEZ', 'Ordinario - Alta', 'Ordinaria',
   'En IM', '2026-09-08', null,
   'En IM con fecha 08/09/2026.'),

  (8, '33501-0010',
   'Estudios de cumplimiento ambiental para el Aeropuerto Internacional Felipe Ángeles.',
   15573480.00, 'Subdirección de Ingeniería', 'Gerencia de Ingeniería Civil',
   'MONSERRAT ALONSO MARTÍNEZ', 'Normativo', 'Ordinaria',
   'En IM', '2026-08-28', null,
   'En IM con fecha 28/08/2026.'),

  (9, '35102-0003',
   'Servicio de mantenimiento a techumbres',
   16042500.00, 'Subdirección de Ingeniería', 'Gerencia de Ingeniería Civil',
   'SANDY OSIRIS MENDONZA LEONÍDEZ', 'Ordinario - Media', 'Ordinaria',
   'En IM', '2026-09-04', null,
   'En IM con fecha 04/09/2026.'),

  (10, '35701-0001',
   'Servicio de mantenimiento y soporte técnico al sistema de iluminación de ayudas visuales.',
   50000000.00, 'Subdirección de Ingeniería', 'Gerencia de Ingeniería Electromecánica',
   'GILBERTO AYALA RAMÍREZ', 'Normativo', 'Ordinaria',
   'En IM', '2026-08-21', null,
   'En IM con fecha 21/08/2026.'),

  (11, '31201-0001',
   'Suministro de gas natural para la central de cogeneración en el Aeropuerto Internacional Felipe Ángeles.',
   125000000.00, 'Subdirección de Gestión Energética', 'Gerencia de Generación',
   'IRMA KARINA VARGAS GARCÍA', 'Ordinario - Alta', 'Ordinaria',
   'En IM', '2026-08-21', null,
   'En IM con fecha 21/08/2026.'),

  (12, '33903-0012',
   'Servicio integral de mantenimiento preventivo y correctivo para la central de cogeneración del Aeropuerto Internacional Felipe Ángeles.',
   38704070.00, 'Subdirección de Gestión Energética', 'Gerencia de Generación',
   'GILBERTO AYALA RAMÍREZ', 'Ordinario - Alta', 'Ordinaria',
   'En IM', '2026-08-28', null,
   'En IM con fecha 28/08/2026.'),

  (13, '35701-0001',
   'Servicio de mantenimiento y conservación a equipos electrógenos (Plantas de Emergencia).',
   25080794.00, 'Subdirección de Gestión Energética', 'Gerencia de Distribución',
   'LILIÁN ELIZABETH PÉREZ GONZÁLEZ', 'Ordinario - Alta', 'Ordinaria',
   'Validación de IM por el área técnica', '2026-08-20', '2026-09-14',
   'En IM con fecha 20/08/2026. Cambio de nombre 03/09/2026. Validación de área 14/09/2026 (IM realizada).'),

  (14, '35701-0001',
   'Servicio de mantenimiento y conservación a los sistemas eléctricos de media tensión para el suministro de energía eléctrica del AIFA.',
   18663820.00, 'Subdirección de Gestión Energética', 'Gerencia de Distribución',
   'ADRIANA PEREZ MALDONADO', 'Ordinario - Alta', 'Ordinaria',
   'En IM', '2026-08-31', null,
   'En IM con fecha 31/08/2026.'),

  (15, '35701-0001',
   'Servicio de Mantenimiento y conservación al Sistema Eléctrico de alta tensión en el Aeropuerto Internacional Felipe Ángeles.',
   15338292.00, 'Subdirección de Gestión Energética', 'Gerencia de Distribución',
   'LILIÁN ELIZABETH PÉREZ GONZÁLEZ', 'Normativo', 'Ordinaria',
   'En IM', '2026-08-24', null,
   'En IM con fecha 24/08/2026.'),

  (16, '35701-0001',
   'Servicio de Mantenimiento y Soporte Técnico al Sistema de Manejo de Equipo BHS (Baggage Handling System).',
   41755953.00, 'Subdirección de Ingeniería', 'Gerencia de Ingeniería Electromecánica',
   'DAYREN FLORICELA DE LEÓN GONZÁLEZ', 'Ordinario - Alta', 'Ordinaria',
   'En IM', '2026-08-21', null,
   'En IM con fecha 21/08/2026. Se entregaron correcciones relacionadas al cambio de nombre del servicio con fecha 28/08/2026.'),

  (17, '35701-0001',
   'Servicio de Mantenimiento y Soporte Técnico a Aeropasillos y sus Servicios Auxiliares',
   13697610.00, 'Subdirección de Seguridad Operacional', 'Gerencia de Operaciones Parte Aeronáutica',
   'SANDY OSIRIS MENDONZA LEONÍDEZ', 'Ordinario - Alta', 'Ordinaria',
   'En IM', '2026-08-21', null,
   'En IM con fecha 21/08/2026.'),

  (18, '35501-0005',
   'Mantenimiento y conservación de 5 (cinco) vehículos STRIKER 6x6',
   2153984.00, 'Subdirección de Seguridad Operacional', 'Gerencia de Seguridad Operacional',
   'GILBERTO AYALA RAMÍREZ', 'Normativo', 'Ordinaria',
   'En IM', '2026-08-20', null,
   'En IM con fecha 20/08/2026.'),

  (19, '35901-0003',
   'Servicio de rescate y control de fauna en el Aeropuerto Internacional Felipe Ángeles',
   19785888.00, 'Subdirección de Seguridad Operacional', 'Gerencia de Seguridad Operacional',
   'LILIÁN ELIZABETH PÉREZ GONZÁLEZ', 'Normativo', 'Ordinaria',
   'En IM', '2026-08-25', null,
   'En IM con fecha 25/08/2026.'),

  (20, '33901-0010',
   'Atención médica prehospitalaria en el AIFA',
   38916833.00, 'Subdirección de Seguridad Operacional', 'Gerencia de Servicio Médico',
   'ESMERALDA EMILY RODRÍGUEZ MARTÍNEZ', 'Ordinario - Alta', 'Ordinaria',
   'En IM', '2026-09-01', null,
   'En IM con fecha 01/09/2026.'),

  (21, '35701-0001',
   'Servicio de mantenimiento preventivo y correctivo para equipos de inspección.',
   26969800.00, 'Subdirección de Seguridad de la Aviación', 'Gerencia de Seguridad',
   'SANDY OSIRIS MENDONZA LEONÍDEZ', 'Ordinario - Alta', 'Ordinaria',
   'En IM', '2026-08-24', null,
   'En IM con fecha 24/08/2026.')
on conflict ("ID") do nothing;

-- Los 21 renglones entraron con "ID" explícito, así que la secuencia de la
-- columna IDENTITY sigue en 1 y el siguiente alta chocaría con el servicio 1.
-- Esto la deja apuntando después del último.
select setval(
  pg_get_serial_sequence('public.estatus_2027', 'ID'),
  greatest(coalesce((select max("ID") from public.estatus_2027), 0), 1),
  true
);

-- -----------------------------------------------------------------------------
-- 5) Seguridad: RLS por rol
--
-- El rol vive en public.profiles. Leerlo desde una política sobre otra tabla
-- exige SECURITY DEFINER: si la política consultara profiles directamente, la
-- RLS de profiles se evaluaría otra vez y Postgres corta por recursión.
-- search_path fijo para que nadie pueda anteponer un esquema propio con una
-- tabla profiles falsa.
-- -----------------------------------------------------------------------------
create or replace function public.current_app_role()
returns text
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select p.role from public.profiles p where p.id = auth.uid()
$$;

revoke all on function public.current_app_role() from public, anon;
grant execute on function public.current_app_role() to authenticated;

alter table public.estatus_2027 enable row level security;

-- La llave anónima viaja dentro del JavaScript que sirve el sitio: cualquiera
-- la puede sacar con abrir las herramientas del navegador. Por eso anon no
-- toca esta tabla ni para leer.
revoke all on public.estatus_2027 from anon, public;
grant select, insert, update, delete on public.estatus_2027 to authenticated;

drop policy if exists estatus_2027_select on public.estatus_2027;
create policy estatus_2027_select
  on public.estatus_2027 for select
  to authenticated
  using (true);

drop policy if exists estatus_2027_insert on public.estatus_2027;
create policy estatus_2027_insert
  on public.estatus_2027 for insert
  to authenticated
  with check (public.current_app_role() in ('ADMIN', 'OPERATOR'));

drop policy if exists estatus_2027_update on public.estatus_2027;
create policy estatus_2027_update
  on public.estatus_2027 for update
  to authenticated
  using (public.current_app_role() in ('ADMIN', 'OPERATOR'))
  with check (public.current_app_role() in ('ADMIN', 'OPERATOR'));

-- Borrar un servicio del programa anual sólo lo hace un administrador.
drop policy if exists estatus_2027_delete on public.estatus_2027;
create policy estatus_2027_delete
  on public.estatus_2027 for delete
  to authenticated
  using (public.current_app_role() = 'ADMIN');

-- -----------------------------------------------------------------------------
-- 6) La bitácora existe (si ya la creaste con scripts/create_change_history_table.sql
--    esto no hace nada)
-- -----------------------------------------------------------------------------
create table if not exists public.change_history (
  id              bigint generated always as identity primary key,
  table_name      text not null,
  record_id       text,
  action          text not null check (action in ('INSERT', 'UPDATE', 'DELETE')),
  changed_by      text,
  changed_by_name text,
  changed_by_role text,
  changes         jsonb,
  previous_data   jsonb,
  new_data        jsonb,
  created_at      timestamptz not null default timezone('utc', now())
);

create index if not exists change_history_created_at_idx on public.change_history (created_at desc);
create index if not exists change_history_table_idx      on public.change_history (table_name);

-- -----------------------------------------------------------------------------
-- 7) Bitácora escrita por la base, no por el navegador
--
-- Hoy el historial lo inserta el cliente (logChange en Dashboard.tsx) con el
-- changed_by que él mismo decide: quien quiera puede firmar un cambio con el
-- id de otra persona. Aquí el autor sale de auth.uid(), que viene del token
-- firmado por Supabase y no se puede falsear desde el navegador. Además queda
-- registrado lo que pase por la API directa, no sólo lo que pase por la app.
--
-- El formato de "changes" es el mismo arreglo {field, before, after} que ya
-- pinta la pestaña Historial.
-- -----------------------------------------------------------------------------
create or replace function public.estatus_2027_audit()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_old     jsonb := case when tg_op = 'INSERT' then null else to_jsonb(old) end;
  v_new     jsonb := case when tg_op = 'DELETE' then null else to_jsonb(new) end;
  v_changes jsonb;
  v_actor   uuid  := auth.uid();
  v_name    text;
  v_role    text;
  v_record  text  := coalesce(v_new ->> 'ID', v_old ->> 'ID');
begin
  select p.full_name, p.role into v_name, v_role
    from public.profiles p where p.id = v_actor;

  if tg_op = 'UPDATE' then
    select jsonb_agg(jsonb_build_object('field', k, 'before', v_old -> k, 'after', v_new -> k))
      into v_changes
      from jsonb_object_keys(v_old || v_new) as k
      -- updated_at cambia en cada guardado; anotarlo sólo ensucia la bitácora.
     where k <> 'updated_at'
       and (v_old -> k) is distinct from (v_new -> k);
    -- Un UPDATE que no cambió nada no merece renglón.
    if v_changes is null then return new; end if;
  else
    select jsonb_agg(jsonb_build_object(
             'field', k,
             'before', case when tg_op = 'DELETE' then v_old -> k else null end,
             'after',  case when tg_op = 'INSERT' then v_new -> k else null end))
      into v_changes
      from jsonb_object_keys(coalesce(v_new, v_old)) as k;
  end if;

  insert into public.change_history (
    table_name, record_id, action, changed_by, changed_by_name, changed_by_role,
    changes, previous_data, new_data
  ) values (
    'estatus_2027', v_record, tg_op, v_actor::text, v_name, v_role,
    v_changes, v_old, v_new
  );

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

revoke all on function public.estatus_2027_audit() from public, anon;

drop trigger if exists estatus_2027_audit_trg on public.estatus_2027;
create trigger estatus_2027_audit_trg
  after insert or update or delete on public.estatus_2027
  for each row execute function public.estatus_2027_audit();

commit;

-- =============================================================================
-- VERIFICACIÓN — correr después, debe devolver 21 servicios y $661,779,577.00
-- =============================================================================
-- select count(*) as servicios,
--        to_char(sum("Monto solicitado anteproyecto 2027"), 'FM$999,999,999.00') as monto_total
--   from public.estatus_2027;
--
-- select "Estatus", count(*) from public.estatus_2027 group by 1 order by 2 desc;
--
-- -- Que anon no pueda leerla (debe decir false):
-- select has_table_privilege('anon', 'public.estatus_2027', 'SELECT');
